### ISSUE TITLE
How you figured out the memory addresses?

### ISSUE THREAD

**Issue by ProgrammerB** [ChrisFischer-MTA/ConquoringConjuration#1]
I was just curious if you could tell me your process for how you went about finding the memory addresses and determining what they went to? Didn't know any other way to reach you other than posting an issue

**Comment by ChrisFischer-MTA** [comment]
Hello,

Thanks for reaching out. I'm writing something up right now. Give me a few minutes.

**Comment by ChrisFischer-MTA** [comment]
Hello,

I'm not very proud of how I got the addresses. Please understand I made this project as my "Intro to C Final" my first year of college. How I personally got the addresses was I used a tool called cheat engine, I would slow the time down in game, then I would look at the top left tile. I went about selecting "Unknown Initial Value". I would then change the tile by playing the game, scan it again saying it's changed, then play the game more to get the original tile in the first scan. I would then select "Compare to first scan" and "Unchanged value". I got a few values, then changed the values until I hit my tile. Once I did, I changed the tiles value from 1 to 25, noting down the value of every single image.

I then scanned for the addresses of the tiles in the first and last of the first few rows, found the pattern, and coded that in the program.

If this is insufficient, or you'd like help in discord, re-open this and send me your question and/or your discord.
